name: yo_style
version: 0.0.1
description: A new Flutter package project.
environment: 
  sdk: '>=2.17.6 <3.0.0'
  flutter: '>=1.17.0'

dependencies: 
  intl: 0.17.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: null
